[app]
    appEnv                = "default"
    serviceName           = "loan-app"
    hostname              = "loan-app.roguexray007.com"
    port                  = ":9400"
    metricPort            = ":8001"
    shutdownTimeout       = 60
    shutdownDelay         = 10
    gitCommitHash         = "nil"
    debug                 = false

[db]
    [db.master]
        dialect               = "mysql"
        protocol              = "tcp"
        url                   = "127.0.0.1"
        port                  = "3306"
        username              = "loan_app"
        password              = "loan_app"
        sslMode               = "require"
        name                  = "loan_app"
        maxOpenConnections    = 50
        maxIdleConnections    = 50
        connectionMaxLifetime = 0
    [db.replica]
        dialect               = "mysql"
        protocol              = "tcp"
        url                   = "127.0.0.1"
        port                  = "3306"
        username              = "loan_app"
        password              = "loan_app"
        sslMode               = "require"
        name                  = "loan_app"
        maxOpenConnections    = 50
        maxIdleConnections    = 50
        connectionMaxLifetime = 0

[redis]
    host              = "localhost"
    port              = 6379
    password          = ""
    database          = 0
    dialect           = "redis"
